# See http://docs.travis-ci.com/user/languages/csharp/ for details

language: csharp
mono:
- latest
dotnet: 2.0.0
dist: trusty

# We need to install the .NET Core 1.0 runtime to run netcoreapp1.0
# tests.
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-sharedframework-microsoft.netcore.app-1.0.5

# xamarinios10 and monoandroid44 are out of build, as not sure if they work.
# net452 is out of testing, as dotnet test does not like it.
script:
- set -e
- export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
- dotnet build ReStructuredText.sln
- cd Tests
- dotnet test
