# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

jobs:
- job: Linux

  pool:
    vmImage: 'ubuntu-latest'

  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - script: |
      set -e
      dotnet build ReStructuredText.sln --configuration $(buildConfiguration)
      dotnet test Tests/Tests.csproj --configuration $(buildConfiguration) --no-build

- job: macOS

  pool:
    vmImage: 'macOS-latest'

  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - script: |
      set -e
      dotnet build ReStructuredText.sln --configuration $(buildConfiguration)
      dotnet test Tests/Tests.csproj --configuration $(buildConfiguration) --no-build

- job: Windows

  pool:
    vmImage: 'windows-latest'

  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - script: |
      dotnet build ReStructuredText.sln --configuration $(buildConfiguration)
      dotnet test Tests/Tests.csproj --configuration $(buildConfiguration) --no-build
